### ISSUE TITLE
[Bug]: 응애

### ISSUE THREAD

**Issue by hafnium1923** [woowacourse-teams/2023-team-by-team#1]
### What happened?

A bug happened!
![다이진](https://github.com/woowacourse-teams/2023-team-by-team/assets/79538610/c0c5eb5d-b5fd-4469-9849-6584b2a3d3a3)

### Version

1.0.2 (Default)

### What browsers are you seeing the problem on?

Chrome

### Relevant log output

```shell
const input = require("fs")
  .readFileSync("example.txt")
  .toString()
  .split("\n")
  .map(Number);

const people = input[0];

const allAnswer = input.slice(1);

const cuteAnswer = allAnswer.reduce((acc, result) => {
  return acc + result;
}, 0);

const answer =
  cuteAnswer > people - cuteAnswer ? "Junhee is cute!" : "Junhee is not cute!";

console.log(answer);
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by pilyang** [comment]
로또 당첨되게 해주세요!!!
