### ISSUE TITLE
[BE] 프로젝트 세팅

### ISSUE THREAD

**Issue by pilyang** [woowacourse-teams/2023-team-by-team#13]
## 구현기능

- 프로젝트 세팅
    - 자바 17
    - 코드컨벤션 파일 적용
    - 필요 디펜던시
        - 스프링부트 3.1.1
            - 스프링 웹
        - 롬복
        - H2
        - JPA
        - 스프링 validation
        - rest-assured
        - Spring RestDocs

### 추정 기간

30분

**Comment by sh111-coder** [comment]
**실제 시간 : 50분 ^^**
