### ISSUE TITLE
[BE] 일정 추가 기능 구현

### ISSUE THREAD

**Issue by pilyang** [woowacourse-teams/2023-team-by-team#18]
## 구현기능

- 사용자가 소속된 팀플레이스의 팀 공유일정을 추가

### 예외 사항

- 일정 이름 제한 : 공백 불가
- 시작  일시가 종료 일시보다 먼저여야 한다.

---

### 추정 시간

공통 스토리포인트 : 1 (2시간)
assignee 추정 시간 : `3시간`

**Comment by sh111-coder** [comment]
* Span에서 @AllArgsContructor 삭제, 모든 파라미터를 받는 생성자에 검증 로직 추가
* Request로 요청보낸 `StartDateTime`, `EndDateTime`의 형식도 검증한다. 
* GlobalExceptionHandler 추가 (+ Handle 시 에러 로깅 추가)

**Comment by sh111-coder** [comment]
실제 작업 시간 : 8시간
