### ISSUE TITLE
[BE] 일정 삭제 기능 구현 

### ISSUE THREAD

**Issue by pilyang** [woowacourse-teams/2023-team-by-team#23]
## 구현기능

- 사용자가 소속된 팀플레이스의 팀 일정을 삭제할 수 있다

### 예외 사항

---

### 추정 시간

공통 스토리포인트 : 2 (4시간)
assignee 추정 시간 : `담당자 배정 후 추가`

**Comment by SproutMJ** [comment]
2시간 반
