### ISSUE TITLE
[BE] 멤버 도메인 작성

### ISSUE THREAD

**Issue by pilyang** [woowacourse-teams/2023-team-by-team#25]
## 구현기능

- 멤버 도메인을 작성한다

## 주의사항

- 프로필 이미지 관련 기능은 로그인 / 회원정보 수정시 고려

### 예외 사항

- 사용자 이름 길이 : 공백이 아닌 20자 이내 문자

---

### 추정 시간

assignee 추정 시간 : 0.5 시간

**Comment by sh111-coder** [comment]
실제 시간 : 1시간
