### ISSUE TITLE
[BE] 멤버 테스트용 더미데이터 추가

### ISSUE THREAD

**Issue by pilyang** [woowacourse-teams/2023-team-by-team#26]
## 구현기능

- 멤버 테스트용 더미데이터 추가

- `data.sql` 파일에 추가

## 주의사항

- `data.sql`은 test directory하위에 추가
- production, develop 인스턴스에서 자동으로 추가되지 않도록 주의
- develop 서버에 더미데이터 추가시 직접 접속해서 추가

---

## 추정 시간

assignee 추정 시간 : 0.5시간

**Comment by SproutMJ** [comment]
실제 시간: 20분
