### ISSUE TITLE
[BE] 팀플레이스 가입 기능

### ISSUE THREAD

**Issue by pilyang** [woowacourse-teams/2023-team-by-team#284]
## 구현기능

- 초대링크를 통해 팀플레이스 가입 기능 구현
- 팀플레이스 가입시 팀플레이스에 추가해줄 색상코드를 본인이 속한 팀플레이스들에서 겹치지 않도록 배정해주도록 구현

## 주의사항

고민해야할 상황
- 해당 링크를 클릭해서 가입할 수 도 있고, 초대링크를 입력해서 로그인 할 수 있다고 생각함 이때 고려해야할 상황
  - 링크 클릭을 가정한다면 response로 ok가 아닌 redirect를 해주어야 하는게 아닌가 생각
  - 해당부분은 회의 후 진행

**Comment by SproutMJ** [comment]
3시간
