### ISSUE TITLE
[BE] 멤버의 팀플레이스 소속 권한 확인 기능 구현

### ISSUE THREAD

**Issue by pilyang** [woowacourse-teams/2023-team-by-team#30]
## 구현기능

- 팀플레이스 관련 기능 사용시, 요청 멤버가 해당 팀플레이스 소속인가 확인하는 기능 구현

## 주의사항

- 해당 검증 위치에 대한 고민 필요
  - filter, interceptor, argument resolver, service layer 또는 domain

---

## 추정 시간

assignee 추정 시간 : `배정 후 작성`

**Comment by SproutMJ** [comment]
4.5 시간
