### ISSUE TITLE
당일 일정도 설정해주면 좋을 것 같습니다

### ISSUE THREAD

**Issue by java-saeng** [woowacourse-teams/2023-team-by-team#343]
### 어떤 버그가 발생했나요?

![image](https://github.com/woowacourse-teams/2023-team-by-team/assets/62413589/cc210edd-fa0e-4a12-bc2e-25ff829dc7cd)

당일 완료해야하는 일정도 있을 것 같아서요,,

### 어떤 브라우저에서 버그가 발생했나요?

Chrome

**Comment by suyoungj** [comment]
핫픽스 완료했습니다 감사합니다 (__)
