### ISSUE TITLE
[ALL | 버그] 하루 동안만 유지되는 종일 일정 생성 불가 오류

### ISSUE THREAD

**Issue by hyeonjerry** [woowacourse-teams/2023-team-by-team#344]
### 어떤 버그가 발생했나요?

하루 동안만 종일 옵션을 선택할 경우 다음과 같은 메시지가 출력되며 일정을 생성할 수 없습니다.
<img width="1306" alt="image" src="https://github.com/woowacourse-teams/2023-team-by-team/assets/71651608/bc1749fc-af0e-444d-97bf-12a30aac9850">

그러나 생성된 일정을 편집하여 하루 동안 종일로 지정할 경우 성공적으로 일정이 수정됩니다.
<img width="1306" alt="image" src="https://github.com/woowacourse-teams/2023-team-by-team/assets/71651608/61c0adb1-c419-4566-818a-966da51ff532">

### 어떤 브라우저에서 버그가 발생했나요?

Chrome

**Comment by suyoungj** [comment]
핫픽스 완료했습니다 감사합니다 (__) https://github.com/woowacourse-teams/2023-team-by-team/pull/347
