### ISSUE TITLE
[FE] 전체 캘린더 뷰에서 회색 박스 크기가 이상함 

### ISSUE THREAD

**Issue by hong-sile** [woowacourse-teams/2023-team-by-team#345]
### 어떤 버그가 발생했나요?

버그? 랄진 모르겠지만,
화면에서
![image](https://github.com/woowacourse-teams/2023-team-by-team/assets/32128848/017d0af2-5972-4c29-9679-f051ec34346b)
간격이 조금 맞춰졌으면 좋겠습니다.

### 어떤 브라우저에서 버그가 발생했나요?

Chrome

**Comment by hafnium1923** [comment]
감사합니다 해결했습니다
