### ISSUE TITLE
[FE] 화면 크기 100%로 설정 시 스크롤바가 중복 표시

### ISSUE THREAD

**Issue by hong-sile** [woowacourse-teams/2023-team-by-team#349]
### 어떤 버그가 발생했나요?

![image](https://github.com/woowacourse-teams/2023-team-by-team/assets/32128848/ae57e1b9-5ca8-4f8c-b2ab-f74f3700aa7a)

크롬에서 화면 크기 100%로 설정 시 가로 스크롤 바와 세로 스크롤 바가 두 개 중복 표시 됩니다.

### 어떤 브라우저에서 버그가 발생했나요?

Chrome

**Comment by hafnium1923** [comment]
감사합니다 해결했습니다.
