### ISSUE TITLE
[FE] 날짜 숫자를 눌렀을때  일정이 뜨는 모달창이 일정하게 뜨지 않는 버그

### ISSUE THREAD

**Issue by chaewon121** [woowacourse-teams/2023-team-by-team#351]
### 어떤 버그가 발생했나요?

달력에 숫자를 눌렀을때 일정이 뜨는 모달창이 위로 뜨는 곳들이 있는데 이것이 일정하지 않습니다.
<img width="1470" alt="image" src="https://github.com/woowacourse-teams/2023-team-by-team/assets/80631952/63a0a457-aa19-4870-ae1a-2a79cee6bfdb">
<img width="1470" alt="image" src="https://github.com/woowacourse-teams/2023-team-by-team/assets/80631952/2487f91d-0f60-47f3-a81a-7566c157fb26">

**Comment by hafnium1923** [comment]
감사합니다. 해결중입니다.
