### ISSUE TITLE
[FE | ALL | 버그] 

### ISSUE THREAD

**Issue by tmdgh1592** [woowacourse-teams/2023-team-by-team#352]
### 어떤 버그가 발생했나요?

버그가 발생했어요!

아래 사진처럼 장문의 글을 추가/삭제하는 경우 변경되지 않습니다.
의도하신 것인지는 모르겠지만, 만약 글자수 제한을 두신 것이라면 경고 문구가 출력되었으면 좋겠어요!

<img width="821" alt="스크린샷 2023-08-07 오후 2 03 20" src="https://github.com/woowacourse-teams/2023-team-by-team/assets/56534241/760fd309-a605-4f95-89a3-4cc22d37cd94">

### 어떤 브라우저에서 버그가 발생했나요?

Chrome

**Comment by hafnium1923** [comment]
감사합니다 곧 반영될 예정입니다
