### ISSUE TITLE
[BE] 로깅, 모니터링 적용 

### ISSUE THREAD

**Issue by SproutMJ** [woowacourse-teams/2023-team-by-team#380]
## 구현기능
- 로깅 프레임워크 적용
- (로그, 매트릭) 모니터링 대시보드 구성

**Comment by pilyang** [comment]
- 로그에 요청 정보 담기
  - ex) "조회한 일정 정보가 없습니다. 조회한 일정 아이디 : 1, 조회한 사용자 : test@email.com"
  - ex) "조회한 일정 정보가 없습니다. 조회한 일정 아이디 : 1:"

-> request에 있는 확인 가능한 정보들만 추가



- CUD 서비스에 로깅 추가 (info)
- EVENT publish, listen 시 로깅 추가 (info)
