### ISSUE TITLE
[FE] <Menu> 컴포넌트의 키보드 탐색 기능을 구현한다.

### ISSUE THREAD

**Issue by suyoungj** [woowacourse-teams/2023-team-by-team#608]
## 구현기능
- <Menu> 컴포넌트의 키보드 탐색 기능을 구현하여 접근성을 개선한다.

**Comment by wzrabbit** [comment]
`Menu` 컴포넌트의 키보드 탐색 기능 구현은 무슨 뜻이야? 혹시 웹 접근성과 관련 있는 기능이야?
화살표 키 누르면 메뉴에서 선택되는 항목을 바꿀 수 있는 기능을 의미하는 거야?

**Comment by suyoungj** [comment]
HTML <select> 처럼 키보드로 포커스 이동이 가능하고, 엔터로 선택 가능하게 한다는 의미야! @wzrabbit

**Comment by wzrabbit** [comment]
<img src="https://user-images.githubusercontent.com/87642422/233928933-505b06b9-5460-4d73-bf1b-4addd84c9e9a.png" width="35px" />
