### ISSUE TITLE
[FE] 채팅에 링크 올리면 자동으로 하이퍼링크 전환

### ISSUE THREAD

**Issue by hafnium1923** [woowacourse-teams/2023-team-by-team#841]
## 주의사항
작업 바로 가능할 때 Assignee 걸기
바빠서 못하면 Assignee 삭제하기

**Comment by wzrabbit** [comment]
이미 해결한 #896 와 동일한 이슈이므로 이 이슈는 해결된 것으로 처리하고 닫을게!
